/* ====================================== */
/* NIHAM HealthWise - Diseases Database   */
/* ====================================== */

const DISEASES_DATA = [
  {
    id: "fever",
    name: "Fever 🤒",
    severity: "Low–Medium",
    diet: "Fluids, fruits, light meals",
    med: "Paracetamol, rest",
    time: "2–5 days",
    curable: "Yes",
    remedy: "fever",
    remedyText: "Hydration, tulsi tea, rest, sponge baths for high fever.",
  },
  {
    id: "commoncold",
    name: "Common Cold🥶",
    severity: "Low",
    diet: "Warm fluids, vitamin C",
    med: "Antihistamines, decongestants",
    time: "5–10 days",
    curable: "Yes",
    remedy: "cold",
    remedyText: "Honey-lemon, steam inhalation, ginger tea.",
  },
  {
    id: "influenza",
    name: "Influenza (Flu)😷",
    severity: "Moderate",
    diet: "Soups, liquids",
    med: "Antivirals in selected cases",
    time: "7–14 days",
    curable: "Yes",
    remedy: "flu",
    remedyText: "Rest, elderberry (supportive), fluids.",
  },
  {
    id: "diabetes",
    name: "Diabetes (Type 2)🔵",
    severity: "Moderate",
    diet: "Low sugar, high fiber, whole grains",
    med: "Metformin, Insulin",
    time: "Ongoing",
    curable: "Manageable",
    remedy: "diabetes",
    remedyText: "Low-GI diet, cinnamon, fenugreek (with medical care).",
  },
  {
    id: "hypertension",
    name: "Hypertension❤️‍🩹",
    severity: "Moderate",
    diet: "Low sodium, potassium-rich foods",
    med: "ACE inhibitors, beta blockers",
    time: "Ongoing",
    curable: "Manageable",
    remedy: "hypertension",
    remedyText: "Garlic, hibiscus tea, celery seed infusion.",
  },
  {
    id: "asthma",
    name: "Asthma🫁",
    severity: "Variable",
    diet: "Avoid triggers, anti-inflammatory foods",
    med: "Inhalers, corticosteroids",
    time: "Chronic",
    curable: "Manageable",
    remedy: "asthma",
    remedyText: "Breathing exercises (Buteyko), turmeric in diet.",
  },
  {
    id: "pneumonia",
    name: "Pneumonia🤧",
    severity: "High",
    diet: "Soups, protein",
    med: "Antibiotics if bacterial",
    time: "2–4 weeks",
    curable: "Yes",
    remedy: "pneumonia",
    remedyText: "Chest physiotherapy after acute phase, ginger soups.",
  },
  {
    id: "tb",
    name: "Tuberculosis (TB)🫁",
    severity: "High",
    diet: "High-protein, calorie-dense",
    med: "RIPE therapy",
    time: "6–9 months",
    curable: "Yes",
    remedy: "tb",
    remedyText: "Nutrition support (medical therapy essential).",
  },
  {
    id: "covid",
    name: "COVID-19😷",
    severity: "Variable",
    diet: "Fluids, good nutrition",
    med: "Supportive care",
    time: "2–3 weeks",
    curable: "Usually",
    remedy: "covid",
    remedyText: "Rest, hydration, graded rehab for long COVID.",
  },
  {
    id: "malaria",
    name: "Malaria",
    severity: "High",
    diet: "Hydration, iron as needed",
    med: "Artemisinin-based therapy",
    time: "2–3 weeks",
    curable: "Yes",
    remedy: "malaria",
    remedyText: "Prompt medical treatment; rest and fluids.",
  },
  {
    id: "dengue",
    name: "Dengue",
    severity: "High",
    diet: "Fluids, ORS",
    med: "Supportive care",
    time: "1–2 weeks",
    curable: "Yes",
    remedy: "dengue",
    remedyText: "Oral rehydration, papaya leaf juice in some settings.",
  },
  {
    id: "typhoid",
    name: "Typhoid",
    severity: "High",
    diet: "Soft foods, fluids",
    med: "Antibiotics",
    time: "2–3 weeks",
    curable: "Yes",
    remedy: "typhoid",
    remedyText: "Hydration, follow prescribed antibiotics.",
  },
  {
    id: "hepatitis",
    name: "Hepatitis",
    severity: "Variable",
    diet: "Low alcohol, low fat",
    med: "Antivirals if indicated",
    time: "Weeks-months",
    curable: "Sometimes",
    remedy: "hepatitis",
    remedyText: "Avoid alcohol; antioxidant-rich foods.",
  },
  {
    id: "arthritis",
    name: "Arthritis",
    severity: "Moderate",
    diet: "Omega-3, anti-inflammatory",
    med: "NSAIDs, physio",
    time: "Ongoing",
    curable: "Manageable",
    remedy: "arthritis",
    remedyText: "Turmeric with black pepper, omega-3 supplements.",
  },
  {
    id: "anemia",
    name: "Anemia",
    severity: "Moderate",
    diet: "Iron-rich foods + VitC",
    med: "Iron supplements",
    time: "1–2 months",
    curable: "Yes",
    remedy: "anemia",
    remedyText: "Iron-rich diet, beetroot, spinach with lemon.",
  },
  {
    id: "migraine",
    name: "Migraine",
    severity: "Moderate",
    diet: "Avoid triggers",
    med: "Triptans, pain relief",
    time: "Variable",
    curable: "Manageable",
    remedy: "migraine",
    remedyText: "Magnesium, hydration, identify triggers.",
  },
  {
    id: "obesity",
    name: "Obesity",
    severity: "Moderate",
    diet: "Low-calorie, high-fiber",
    med: "Lifestyle, meds if needed",
    time: "Ongoing",
    curable: "Manageable",
    remedy: "obesity",
    remedyText: "Dietary changes, regular exercise, portion control.",
  },
  {
    id: "ulcer",
    name: "Stomach Ulcer",
    severity: "Moderate",
    diet: "Avoid spicy/acidic",
    med: "PPI, antacids",
    time: "2–6 weeks",
    curable: "Yes",
    remedy: "ulcer",
    remedyText: "Avoid NSAIDs, small bland meals.",
  },
  {
    id: "epilepsy",
    name: "Epilepsy",
    severity: "High",
    diet: "Special diets sometimes",
    med: "Anticonvulsants",
    time: "Variable",
    curable: "Manageable",
    remedy: "epilepsy",
    remedyText: "Medication adherence; specialist diets in some cases.",
  },
  {
    id: "appendicitis",
    name: "Appendicitis",
    severity: "High",
    diet: "NPO if suspected",
    med: "Surgery",
    time: "Weeks post-op",
    curable: "Yes",
    remedy: "appendicitis",
    remedyText: "Surgical treatment — seek emergency care.",
  },
  {
    id: "depression",
    name: "Depression",
    severity: "High",
    diet: "Omega-3 & B-vitamins",
    med: "SSRIs + therapy",
    time: "Weeks-months",
    curable: "Treatable",
    remedy: "depression",
    remedyText: "Exercise, sunlight, therapy, social support.",
  },
  {
    id: "anxiety",
    name: "Anxiety",
    severity: "Moderate",
    diet: "Avoid caffeine",
    med: "Therapy/meds",
    time: "Variable",
    curable: "Treatable",
    remedy: "anxiety",
    remedyText: "Breathing exercises, chamomile, therapy.",
  },
  {
    id: "kidneystone",
    name: "Kidney Stones",
    severity: "Moderate",
    diet: "Hydration, limit salt",
    med: "Pain meds, lithotripsy",
    time: "Days-weeks",
    curable: "Yes",
    remedy: "kidneystone",
    remedyText: "Lemon water, hydration, reduce sodium.",
  },
  {
    id: "copd",
    name: "COPD",
    severity: "High",
    diet: "High calorie if needed",
    med: "Bronchodilators",
    time: "Chronic",
    curable: "Manageable",
    remedy: "copd",
    remedyText: "Smoking cessation, pulmonary rehab.",
  },
  {
    id: "alzheimer",
    name: "Alzheimer's Disease",
    severity: "High",
    diet: "Mediterranean diet",
    med: "Symptomatic meds",
    time: "Chronic",
    curable: "Manageable",
    remedy: "alzheimer",
    remedyText: "Cognitive activities, Mediterranean-style diet.",
  },
  {
    id: "parkinson",
    name: "Parkinson's Disease",
    severity: "High",
    diet: "Protein timing",
    med: "Levodopa",
    time: "Chronic",
    curable: "Manageable",
    remedy: "parkinson",
    remedyText: "Exercise, physical therapy, balance training.",
  },
  {
    id: "cancer",
    name: "Cancer (various)",
    severity: "High",
    diet: "Nutrition support",
    med: "Surgery/chemo/radiation",
    time: "Variable",
    curable: "Depends",
    remedy: "cancer",
    remedyText: "Nutrition during therapy; supportive care.",
  },
  {
    id: "hiv",
    name: "HIV/AIDS",
    severity: "High",
    diet: "Good nutrition",
    med: "ART",
    time: "Chronic",
    curable: "No (manageable)",
    remedy: "hiv",
    remedyText: "ART adherence and healthy diet.",
  },
  {
    id: "rabies",
    name: "Rabies",
    severity: "Critical",
    diet: "N/A",
    med: "Post-exposure prophylaxis",
    time: "N/A",
    curable: "Preventable",
    remedy: "rabies",
    remedyText: "Immediate PEP after animal bite — urgent!",
  },
  {
    id: "tetanus",
    name: "Tetanus",
    severity: "Critical",
    diet: "Supportive",
    med: "Antitoxin/antibiotics",
    time: "Critical",
    curable: "Manageable",
    remedy: "tetanus",
    remedyText: "Immunization and urgent care.",
  },
  {
    id: "acne",
    name: "Acne",
    severity: "Low-Medium",
    diet: "Low-sugar diet",
    med: "Topical retinoids",
    time: "Weeks",
    curable: "Manageable",
    remedy: "acne",
    remedyText: "Aloe-vera, tea-tree oil, avoid oily foods.",
  },
  {
    id: "arthritis",
    name: "Arthritis",
    severity: "Moderate",
    diet: "Omega-3, anti-inflammatory",
    med: "NSAIDs, physio",
    time: "Ongoing",
    curable: "Manageable",
    remedy: "arthritis",
    remedyText: "Turmeric with black pepper, omega-3 supplements.",
  },
  {
    id: "gout",
    name: "Gout",
    severity: "Medium",
    diet: "Low-purine diet",
    med: "NSAIDs, allopurinol",
    time: "Days-weeks",
    curable: "Manageable",
    remedy: "gout",
    remedyText: "Cherry juice, limit purine-rich foods.",
  },
  {
    id: "insomnia",
    name: "Insomnia",
    severity: "Medium",
    diet: "Light dinner, milk",
    med: "Melatonin if prescribed",
    time: "Variable",
    curable: "Treatable",
    remedy: "insomnia",
    remedyText: "Chamomile tea, regular sleep schedule.",
  },
  {
    id: "foodpoisoning",
    name: "Food Poisoning",
    severity: "Medium",
    diet: "Fluids, soft food",
    med: "ORS, antibiotics if severe",
    time: "Days",
    curable: "Yes",
    remedy: "foodpoisoning",
    remedyText: "Hydration, rest, light diet.",
  },
  {
    id: "allergy",
    name: "Allergy",
    severity: "Low-Medium",
    diet: "Avoid trigger foods",
    med: "Antihistamines",
    time: "Variable",
    curable: "Manageable",
    remedy: "allergy",
    remedyText: "Honey (local), vitamin C, avoid triggers.",
  },
  {
    id: "bronchitis",
    name: "Bronchitis",
    severity: "Medium",
    diet: "Warm fluids, honey",
    med: "Cough suppressants, antibiotics if bacterial",
    time: "1-3 weeks",
    curable: "Yes",
    remedy: "bronchitis",
    remedyText: "Steam inhalation, ginger tea, rest.",
  },
  {
    id: "sinusitis",
    name: "Sinusitis",
    severity: "Medium",
    diet: "Spicy foods, fluids",
    med: "Decongestants, nasal sprays",
    time: "1-2 weeks",
    curable: "Yes",
    remedy: "sinusitis",
    remedyText: "Steam inhalation, saline rinse, eucalyptus oil.",
  },
  {
    id: "tonsillitis",
    name: "Tonsillitis",
    severity: "Medium",
    diet: "Soft foods, warm liquids",
    med: "Antibiotics if bacterial",
    time: "5-7 days",
    curable: "Yes",
    remedy: "tonsillitis",
    remedyText: "Salt water gargle, honey, rest.",
  },
  {
    id: "conjunctivitis",
    name: "Conjunctivitis (Pink Eye)",
    severity: "Low",
    diet: "Normal diet",
    med: "Eye drops, antibiotics if bacterial",
    time: "3-7 days",
    curable: "Yes",
    remedy: "conjunctivitis",
    remedyText: "Warm compress, clean eyes regularly.",
  },
  {
    id: "eczema",
    name: "Eczema",
    severity: "Medium",
    diet: "Anti-inflammatory foods",
    med: "Topical steroids, moisturizers",
    time: "Chronic",
    curable: "Manageable",
    remedy: "eczema",
    remedyText: "Coconut oil, oatmeal baths, avoid triggers.",
  },
  {
    id: "psoriasis",
    name: "Psoriasis",
    severity: "Medium",
    diet: "Anti-inflammatory diet",
    med: "Topical treatments, biologics",
    time: "Chronic",
    curable: "Manageable",
    remedy: "psoriasis",
    remedyText: "Aloe vera, sunlight exposure, moisturize.",
  },
  {
    id: "chickenpox",
    name: "Chickenpox",
    severity: "Medium",
    diet: "Soft foods, fluids",
    med: "Antihistamines, calamine lotion",
    time: "1-2 weeks",
    curable: "Yes",
    remedy: "chickenpox",
    remedyText: "Oatmeal baths, neem leaves, rest.",
  },
  {
    id: "measles",
    name: "Measles",
    severity: "High",
    diet: "Vitamin A, fluids",
    med: "Supportive care, vitamin A",
    time: "1-2 weeks",
    curable: "Yes",
    remedy: "measles",
    remedyText: "Rest, hydration, vitamin A supplementation.",
  },
  {
    id: "mumps",
    name: "Mumps",
    severity: "Medium",
    diet: "Soft foods, fluids",
    med: "Pain relievers, rest",
    time: "1-2 weeks",
    curable: "Yes",
    remedy: "mumps",
    remedyText: "Warm/cold compress, soft diet, rest.",
  },
  {
    id: "whoopingcough",
    name: "Whooping Cough",
    severity: "High",
    diet: "Small frequent meals",
    med: "Antibiotics",
    time: "6-10 weeks",
    curable: "Yes",
    remedy: "whoopingcough",
    remedyText: "Honey (for children >1 year), humidifier, rest.",
  },
  {
    id: "diarrhea",
    name: "Diarrhea",
    severity: "Low-Medium",
    diet: "BRAT diet, ORS",
    med: "ORS, probiotics",
    time: "2-3 days",
    curable: "Yes",
    remedy: "diarrhea",
    remedyText: "ORS, yogurt, banana, rice water.",
  },
  {
    id: "constipation",
    name: "Constipation",
    severity: "Low",
    diet: "High fiber, water",
    med: "Laxatives if needed",
    time: "Days",
    curable: "Yes",
    remedy: "constipation",
    remedyText: "Fiber-rich foods, water, prunes, exercise.",
  },
  {
    id: "ibs",
    name: "Irritable Bowel Syndrome",
    severity: "Medium",
    diet: "Low FODMAP diet",
    med: "Antispasmodics",
    time: "Chronic",
    curable: "Manageable",
    remedy: "ibs",
    remedyText: "Peppermint oil, probiotics, stress management.",
  },
  {
    id: "gastritis",
    name: "Gastritis",
    severity: "Medium",
    diet: "Bland foods, avoid spicy",
    med: "Antacids, PPIs",
    time: "1-2 weeks",
    curable: "Yes",
    remedy: "gastritis",
    remedyText: "Ginger tea, avoid alcohol, small meals.",
  },
  {
    id: "gerd",
    name: "GERD (Acid Reflux)",
    severity: "Medium",
    diet: "Avoid acidic/spicy foods",
    med: "PPIs, antacids",
    time: "Ongoing",
    curable: "Manageable",
    remedy: "gerd",
    remedyText: "Elevate head while sleeping, avoid late meals.",
  },
  {
    id: "gallstones",
    name: "Gallstones",
    severity: "Medium-High",
    diet: "Low-fat diet",
    med: "Surgery if symptomatic",
    time: "Variable",
    curable: "Yes (surgery)",
    remedy: "gallstones",
    remedyText: "Apple cider vinegar, lemon juice, low-fat diet.",
  },
  {
    id: "cirrhosis",
    name: "Cirrhosis",
    severity: "High",
    diet: "Low sodium, protein",
    med: "Treat underlying cause",
    time: "Chronic",
    curable: "No (manageable)",
    remedy: "cirrhosis",
    remedyText: "Avoid alcohol, nutritious diet, medical care.",
  },
  {
    id: "uti",
    name: "Urinary Tract Infection",
    severity: "Medium",
    diet: "Cranberry juice, water",
    med: "Antibiotics",
    time: "3-7 days",
    curable: "Yes",
    remedy: "uti",
    remedyText: "Cranberry juice, hydration, vitamin C.",
  },
  {
    id: "ckd",
    name: "Chronic Kidney Disease",
    severity: "High",
    diet: "Low sodium, protein",
    med: "BP control, dialysis",
    time: "Chronic",
    curable: "No (manageable)",
    remedy: "ckd",
    remedyText: "Medical management, diet control, hydration.",
  },
  {
    id: "thyroid",
    name: "Hypothyroidism",
    severity: "Medium",
    diet: "Iodine-rich foods",
    med: "Levothyroxine",
    time: "Lifelong",
    curable: "Manageable",
    remedy: "thyroid",
    remedyText: "Selenium, iodine, regular medication.",
  },
  {
    id: "hyperthyroid",
    name: "Hyperthyroidism",
    severity: "Medium",
    diet: "Low iodine",
    med: "Antithyroid drugs",
    time: "Variable",
    curable: "Treatable",
    remedy: "hyperthyroid",
    remedyText: "Avoid excess iodine, stress management.",
  },
  {
    id: "pcos",
    name: "PCOS",
    severity: "Medium",
    diet: "Low GI, balanced",
    med: "Metformin, hormones",
    time: "Chronic",
    curable: "Manageable",
    remedy: "pcos",
    remedyText: "Exercise, weight management, spearmint tea.",
  },
  {
    id: "endometriosis",
    name: "Endometriosis",
    severity: "Medium-High",
    diet: "Anti-inflammatory",
    med: "Hormones, surgery",
    time: "Chronic",
    curable: "Manageable",
    remedy: "endometriosis",
    remedyText: "Heat therapy, omega-3, turmeric.",
  },
  {
    id: "osteoporosis",
    name: "Osteoporosis",
    severity: "Medium",
    diet: "Calcium, vitamin D",
    med: "Bisphosphonates",
    time: "Chronic",
    curable: "Manageable",
    remedy: "osteoporosis",
    remedyText: "Weight-bearing exercise, calcium, vitamin D.",
  },
  {
    id: "stroke",
    name: "Stroke",
    severity: "Critical",
    diet: "Low sodium, healthy",
    med: "Emergency care, rehab",
    time: "Variable",
    curable: "Depends",
    remedy: "stroke",
    remedyText: "Emergency medical care — time critical!",
  },
  {
    id: "heartattack",
    name: "Heart Attack",
    severity: "Critical",
    diet: "Heart-healthy diet",
    med: "Emergency care",
    time: "Variable",
    curable: "Depends",
    remedy: "heartattack",
    remedyText: "Emergency care immediately — call ambulance!",
  },
  {
    id: "heartfailure",
    name: "Heart Failure",
    severity: "High",
    diet: "Low sodium",
    med: "Diuretics, ACE inhibitors",
    time: "Chronic",
    curable: "Manageable",
    remedy: "heartfailure",
    remedyText: "Medication adherence, low salt, monitor weight.",
  },
  {
    id: "varicoseveins",
    name: "Varicose Veins",
    severity: "Low-Medium",
    diet: "High fiber",
    med: "Compression stockings",
    time: "Chronic",
    curable: "Treatable",
    remedy: "varicoseveins",
    remedyText: "Elevate legs, exercise, compression stockings.",
  },
  {
    id: "aneurysm",
    name: "Aneurysm",
    severity: "Critical",
    diet: "Heart-healthy",
    med: "Surgery if needed",
    time: "Variable",
    curable: "Depends",
    remedy: "aneurysm",
    remedyText: "Medical monitoring, BP control, avoid smoking.",
  },
  {
    id: "meningitis",
    name: "Meningitis",
    severity: "Critical",
    diet: "Supportive",
    med: "Antibiotics/antivirals",
    time: "2-4 weeks",
    curable: "Yes (if treated)",
    remedy: "meningitis",
    remedyText: "Emergency medical care — urgent!",
  },
  {
    id: "encephalitis",
    name: "Encephalitis",
    severity: "Critical",
    diet: "Supportive",
    med: "Antivirals",
    time: "Weeks",
    curable: "Depends",
    remedy: "encephalitis",
    remedyText: "Emergency medical care required.",
  },
  {
    id: "ms",
    name: "Multiple Sclerosis",
    severity: "High",
    diet: "Anti-inflammatory",
    med: "Disease-modifying drugs",
    time: "Chronic",
    curable: "No (manageable)",
    remedy: "ms",
    remedyText: "Vitamin D, omega-3, physical therapy.",
  },
  {
    id: "lupus",
    name: "Lupus",
    severity: "High",
    diet: "Anti-inflammatory",
    med: "Immunosuppressants",
    time: "Chronic",
    curable: "No (manageable)",
    remedy: "lupus",
    remedyText: "Sun protection, anti-inflammatory diet, rest.",
  },
  {
    id: "celiac",
    name: "Celiac Disease",
    severity: "Medium",
    diet: "Gluten-free",
    med: "None (diet only)",
    time: "Lifelong",
    curable: "Manageable",
    remedy: "celiac",
    remedyText: "Strict gluten-free diet.",
  },
  {
    id: "crohns",
    name: "Crohn's Disease",
    severity: "High",
    diet: "Low-residue diet",
    med: "Immunosuppressants",
    time: "Chronic",
    curable: "No (manageable)",
    remedy: "crohns",
    remedyText: "Anti-inflammatory diet, stress management.",
  },
  {
    id: "ulcerativecolitis",
    name: "Ulcerative Colitis",
    severity: "High",
    diet: "Low-fiber during flare",
    med: "Anti-inflammatories",
    time: "Chronic",
    curable: "No (manageable)",
    remedy: "ulcerativecolitis",
    remedyText: "Probiotics, omega-3, stress management.",
  },
  {
    id: "hemorrhoids",
    name: "Hemorrhoids",
    severity: "Low-Medium",
    diet: "High fiber, water",
    med: "Topical creams",
    time: "Days-weeks",
    curable: "Yes",
    remedy: "hemorrhoids",
    remedyText: "Sitz baths, fiber, witch hazel.",
  },
  {
    id: "hernia",
    name: "Hernia",
    severity: "Medium",
    diet: "Small meals",
    med: "Surgery",
    time: "Variable",
    curable: "Yes (surgery)",
    remedy: "hernia",
    remedyText: "Avoid heavy lifting, surgical repair needed.",
  },
  {
    id: "glaucoma",
    name: "Glaucoma",
    severity: "High",
    diet: "Antioxidant-rich",
    med: "Eye drops, surgery",
    time: "Chronic",
    curable: "No (manageable)",
    remedy: "glaucoma",
    remedyText: "Regular eye exams, medication adherence.",
  },
  {
    id: "cataract",
    name: "Cataract",
    severity: "Medium",
    diet: "Antioxidants",
    med: "Surgery",
    time: "Variable",
    curable: "Yes (surgery)",
    remedy: "cataract",
    remedyText: "Antioxidant-rich diet, UV protection.",
  },
  {
    id: "macular",
    name: "Macular Degeneration",
    severity: "High",
    diet: "Leafy greens, fish",
    med: "Injections, supplements",
    time: "Chronic",
    curable: "No (manageable)",
    remedy: "macular",
    remedyText: "Lutein, zeaxanthin, omega-3.",
  },
  {
    id: "tinnitus",
    name: "Tinnitus",
    severity: "Low-Medium",
    diet: "Avoid caffeine",
    med: "Sound therapy",
    time: "Variable",
    curable: "Manageable",
    remedy: "tinnitus",
    remedyText: "White noise, ginkgo biloba, stress reduction.",
  },
  {
    id: "vertigo",
    name: "Vertigo",
    severity: "Medium",
    diet: "Hydration",
    med: "Antihistamines",
    time: "Days-weeks",
    curable: "Yes",
    remedy: "vertigo",
    remedyText: "Epley maneuver, ginger, hydration.",
  },
  {
    id: "bellspalsy",
    name: "Bell's Palsy",
    severity: "Medium",
    diet: "Normal",
    med: "Steroids, antivirals",
    time: "3-6 months",
    curable: "Usually",
    remedy: "bellspalsy",
    remedyText: "Facial exercises, eye protection, massage.",
  },
  {
    id: "shingles",
    name: "Shingles",
    severity: "Medium-High",
    diet: "Immune-boosting",
    med: "Antivirals, pain relief",
    time: "2-4 weeks",
    curable: "Yes",
    remedy: "shingles",
    remedyText: "Cool compresses, calamine lotion, rest.",
  },
  {
    id: "lyme",
    name: "Lyme Disease",
    severity: "Medium-High",
    diet: "Anti-inflammatory",
    med: "Antibiotics",
    time: "2-4 weeks",
    curable: "Yes (if early)",
    remedy: "lyme",
    remedyText: "Early antibiotic treatment essential.",
  },
  {
    id: "sickle",
    name: "Sickle Cell Disease",
    severity: "High",
    diet: "Hydration, folic acid",
    med: "Pain management",
    time: "Lifelong",
    curable: "No (manageable)",
    remedy: "sickle",
    remedyText: "Hydration, avoid triggers, folic acid.",
  },
  {
    id: "hemophilia",
    name: "Hemophilia",
    severity: "High",
    diet: "Normal",
    med: "Clotting factors",
    time: "Lifelong",
    curable: "No (manageable)",
    remedy: "hemophilia",
    remedyText: "Avoid injury, clotting factor replacement.",
  },
  {
    id: "leukemia",
    name: "Leukemia",
    severity: "Critical",
    diet: "Nutritious",
    med: "Chemotherapy",
    time: "Variable",
    curable: "Depends",
    remedy: "leukemia",
    remedyText: "Medical treatment, nutrition support.",
  },
  {
    id: "lymphoma",
    name: "Lymphoma",
    severity: "High",
    diet: "Nutritious",
    med: "Chemotherapy, radiation",
    time: "Variable",
    curable: "Depends",
    remedy: "lymphoma",
    remedyText: "Medical treatment, supportive care.",
  },
  {
    id: "fibromyalgia",
    name: "Fibromyalgia",
    severity: "Medium",
    diet: "Anti-inflammatory",
    med: "Pain relievers, antidepressants",
    time: "Chronic",
    curable: "Manageable",
    remedy: "fibromyalgia",
    remedyText: "Gentle exercise, stress management, magnesium.",
  },
  {
    id: "rosacea",
    name: "Rosacea",
    severity: "Low-Medium",
    diet: "Avoid triggers",
    med: "Topical treatments",
    time: "Chronic",
    curable: "Manageable",
    remedy: "rosacea",
    remedyText: "Green tea, aloe vera, avoid sun exposure.",
  },
  {
    id: "vitiligo",
    name: "Vitiligo",
    severity: "Low",
    diet: "Antioxidant-rich",
    med: "Topical steroids, phototherapy",
    time: "Chronic",
    curable: "Manageable",
    remedy: "vitiligo",
    remedyText: "Sun protection, vitamin B12, copper-rich foods.",
  },
  {
    id: "alopecia",
    name: "Alopecia",
    severity: "Low-Medium",
    diet: "Protein, iron-rich",
    med: "Minoxidil, steroids",
    time: "Variable",
    curable: "Sometimes",
    remedy: "alopecia",
    remedyText: "Onion juice, biotin, scalp massage.",
  },
  {
    id: "dandruff",
    name: "Dandruff",
    severity: "Low",
    diet: "Zinc-rich foods",
    med: "Anti-dandruff shampoo",
    time: "Ongoing",
    curable: "Manageable",
    remedy: "dandruff",
    remedyText: "Tea tree oil, coconut oil, neem.",
  },
  {
    id: "ringworm",
    name: "Ringworm",
    severity: "Low",
    diet: "Normal",
    med: "Antifungal creams",
    time: "2-4 weeks",
    curable: "Yes",
    remedy: "ringworm",
    remedyText: "Tea tree oil, garlic paste, keep area dry.",
  },
  {
    id: "scabies",
    name: "Scabies",
    severity: "Medium",
    diet: "Normal",
    med: "Permethrin cream",
    time: "1-2 weeks",
    curable: "Yes",
    remedy: "scabies",
    remedyText: "Neem oil, tea tree oil, wash all clothing.",
  },
  {
    id: "lice",
    name: "Head Lice",
    severity: "Low",
    diet: "Normal",
    med: "Medicated shampoo",
    time: "1-2 weeks",
    curable: "Yes",
    remedy: "lice",
    remedyText: "Coconut oil, neem oil, fine-tooth comb.",
  },
  {
    id: "warts",
    name: "Warts",
    severity: "Low",
    diet: "Immune-boosting",
    med: "Cryotherapy, salicylic acid",
    time: "Weeks-months",
    curable: "Yes",
    remedy: "warts",
    remedyText: "Apple cider vinegar, garlic, duct tape method.",
  },
  {
    id: "athletes",
    name: "Athlete's Foot",
    severity: "Low",
    diet: "Normal",
    med: "Antifungal cream",
    time: "2-4 weeks",
    curable: "Yes",
    remedy: "athletes",
    remedyText: "Tea tree oil, keep feet dry, garlic.",
  },
  {
    id: "jock",
    name: "Jock Itch",
    severity: "Low",
    diet: "Normal",
    med: "Antifungal cream",
    time: "2-3 weeks",
    curable: "Yes",
    remedy: "jock",
    remedyText: "Keep area dry, tea tree oil, loose clothing.",
  },
  {
    id: "impetigo",
    name: "Impetigo",
    severity: "Medium",
    diet: "Normal",
    med: "Antibiotic ointment",
    time: "1-2 weeks",
    curable: "Yes",
    remedy: "impetigo",
    remedyText: "Keep clean, honey, garlic paste.",
  },
  {
    id: "cellulitis",
    name: "Cellulitis",
    severity: "High",
    diet: "Normal",
    med: "Antibiotics",
    time: "1-2 weeks",
    curable: "Yes",
    remedy: "cellulitis",
    remedyText: "Elevate affected area, warm compress, antibiotics.",
  },
  {
    id: "abscess",
    name: "Abscess",
    severity: "Medium",
    diet: "Normal",
    med: "Drainage, antibiotics",
    time: "1-2 weeks",
    curable: "Yes",
    remedy: "abscess",
    remedyText: "Warm compress, turmeric paste, medical drainage.",
  },
  {
    id: "boils",
    name: "Boils",
    severity: "Low-Medium",
    diet: "Normal",
    med: "Warm compress, antibiotics",
    time: "1-2 weeks",
    curable: "Yes",
    remedy: "boils",
    remedyText: "Warm compress, turmeric, neem leaves.",
  },
  {
    id: "hives",
    name: "Hives (Urticaria)",
    severity: "Low-Medium",
    diet: "Avoid triggers",
    med: "Antihistamines",
    time: "Days-weeks",
    curable: "Yes",
    remedy: "hives",
    remedyText: "Cold compress, oatmeal bath, avoid triggers.",
  },
  {
    id: "angioedema",
    name: "Angioedema",
    severity: "Medium-High",
    diet: "Avoid triggers",
    med: "Antihistamines, epinephrine",
    time: "Hours-days",
    curable: "Yes",
    remedy: "angioedema",
    remedyText: "Emergency care if severe, antihistamines.",
  },
  {
    id: "dermatitis",
    name: "Contact Dermatitis",
    severity: "Low-Medium",
    diet: "Normal",
    med: "Topical steroids",
    time: "1-2 weeks",
    curable: "Yes",
    remedy: "dermatitis",
    remedyText: "Avoid irritant, aloe vera, oatmeal bath.",
  },
  {
    id: "seborrhea",
    name: "Seborrheic Dermatitis",
    severity: "Low-Medium",
    diet: "Anti-inflammatory",
    med: "Medicated shampoo",
    time: "Chronic",
    curable: "Manageable",
    remedy: "seborrhea",
    remedyText: "Tea tree oil, apple cider vinegar, omega-3.",
  },
  {
    id: "keratosis",
    name: "Keratosis Pilaris",
    severity: "Low",
    diet: "Normal",
    med: "Moisturizers, exfoliation",
    time: "Chronic",
    curable: "Manageable",
    remedy: "keratosis",
    remedyText: "Coconut oil, exfoliation, moisturize.",
  },
  {
    id: "melasma",
    name: "Melasma",
    severity: "Low",
    diet: "Antioxidant-rich",
    med: "Topical lightening agents",
    time: "Months-years",
    curable: "Manageable",
    remedy: "melasma",
    remedyText: "Sun protection, aloe vera, vitamin C.",
  },
  {
    id: "sunburn",
    name: "Sunburn",
    severity: "Low-Medium",
    diet: "Hydration",
    med: "Aloe, pain relievers",
    time: "3-7 days",
    curable: "Yes",
    remedy: "sunburn",
    remedyText: "Aloe vera, cool compress, hydration.",
  },
  {
    id: "frostbite",
    name: "Frostbite",
    severity: "High",
    diet: "Warm fluids",
    med: "Rewarming, pain relief",
    time: "Weeks",
    curable: "Depends",
    remedy: "frostbite",
    remedyText: "Gradual rewarming, medical care, avoid rubbing.",
  },
  {
    id: "heatstroke",
    name: "Heat Stroke",
    severity: "Critical",
    diet: "Hydration",
    med: "Emergency cooling",
    time: "Hours-days",
    curable: "Yes (if treated)",
    remedy: "heatstroke",
    remedyText: "Emergency care, cool body, hydration.",
  },
  {
    id: "dehydration",
    name: "Dehydration",
    severity: "Medium",
    diet: "ORS, fluids",
    med: "IV fluids if severe",
    time: "Hours-days",
    curable: "Yes",
    remedy: "dehydration",
    remedyText: "ORS, coconut water, electrolyte drinks.",
  },
  {
    id: "heatexhaustion",
    name: "Heat Exhaustion",
    severity: "Medium",
    diet: "Fluids, electrolytes",
    med: "Rest, cooling",
    time: "Hours-days",
    curable: "Yes",
    remedy: "heatexhaustion",
    remedyText: "Move to cool place, hydration, rest.",
  },
  {
    id: "hypothermia",
    name: "Hypothermia",
    severity: "Critical",
    diet: "Warm fluids",
    med: "Gradual rewarming",
    time: "Hours-days",
    curable: "Yes (if treated)",
    remedy: "hypothermia",
    remedyText: "Gradual warming, warm drinks, medical care.",
  },
  {
    id: "nosebleed",
    name: "Nosebleed (Epistaxis)",
    severity: "Low",
    diet: "Normal",
    med: "Pressure, ice",
    time: "Minutes",
    curable: "Yes",
    remedy: "nosebleed",
    remedyText: "Pinch nose, lean forward, cold compress.",
  },
  {
    id: "earinfection",
    name: "Ear Infection",
    severity: "Medium",
    diet: "Normal",
    med: "Antibiotics if bacterial",
    time: "1-2 weeks",
    curable: "Yes",
    remedy: "earinfection",
    remedyText: "Warm compress, garlic oil, pain relief.",
  },
  {
    id: "swimmer",
    name: "Swimmer's Ear",
    severity: "Low-Medium",
    diet: "Normal",
    med: "Ear drops",
    time: "1 week",
    curable: "Yes",
    remedy: "swimmer",
    remedyText: "Keep ear dry, vinegar-alcohol drops.",
  },
  {
    id: "tmj",
    name: "TMJ Disorder",
    severity: "Medium",
    diet: "Soft foods",
    med: "Pain relievers, splint",
    time: "Variable",
    curable: "Manageable",
    remedy: "tmj",
    remedyText: "Jaw exercises, warm compress, avoid hard foods.",
  },
  {
    id: "gingivitis",
    name: "Gingivitis",
    severity: "Low-Medium",
    diet: "Vitamin C",
    med: "Professional cleaning",
    time: "Weeks",
    curable: "Yes",
    remedy: "gingivitis",
    remedyText: "Salt water rinse, oil pulling, good oral hygiene.",
  },
  {
    id: "periodontitis",
    name: "Periodontitis",
    severity: "Medium",
    diet: "Vitamin C, calcium",
    med: "Deep cleaning, surgery",
    time: "Ongoing",
    curable: "Manageable",
    remedy: "periodontitis",
    remedyText: "Professional care, oil pulling, vitamin C.",
  },
  {
    id: "toothache",
    name: "Toothache",
    severity: "Low-Medium",
    diet: "Soft foods",
    med: "Pain relievers, dental care",
    time: "Variable",
    curable: "Yes",
    remedy: "toothache",
    remedyText: "Clove oil, salt water rinse, see dentist.",
  },
  {
    id: "canker",
    name: "Canker Sores",
    severity: "Low",
    diet: "Avoid acidic foods",
    med: "Topical gels",
    time: "1-2 weeks",
    curable: "Yes",
    remedy: "canker",
    remedyText: "Salt water rinse, honey, avoid spicy foods.",
  },
  {
    id: "thrush",
    name: "Oral Thrush",
    severity: "Low-Medium",
    diet: "Low sugar",
    med: "Antifungal medication",
    time: "1-2 weeks",
    curable: "Yes",
    remedy: "thrush",
    remedyText: "Yogurt, salt water rinse, reduce sugar.",
  },
  {
    id: "laryngitis",
    name: "Laryngitis",
    severity: "Low-Medium",
    diet: "Warm fluids",
    med: "Voice rest, humidifier",
    time: "1-2 weeks",
    curable: "Yes",
    remedy: "laryngitis",
    remedyText: "Voice rest, honey-lemon, steam inhalation.",
  },
  {
    id: "pharyngitis",
    name: "Pharyngitis (Sore Throat)",
    severity: "Low-Medium",
    diet: "Warm liquids",
    med: "Pain relievers, antibiotics if bacterial",
    time: "3-7 days",
    curable: "Yes",
    remedy: "pharyngitis",
    remedyText: "Salt water gargle, honey, warm tea.",
  },
  {
    id: "mononucleosis",
    name: "Mononucleosis (Mono)",
    severity: "Medium",
    diet: "Rest, fluids",
    med: "Supportive care",
    time: "2-4 weeks",
    curable: "Yes",
    remedy: "mononucleosis",
    remedyText: "Rest, hydration, avoid contact sports.",
  },
  {
    id: "strep",
    name: "Strep Throat",
    severity: "Medium",
    diet: "Soft foods, fluids",
    med: "Antibiotics",
    time: "3-7 days",
    curable: "Yes",
    remedy: "strep",
    remedyText: "Antibiotics essential, salt water gargle, rest.",
  },
  {
    id: "croup",
    name: "Croup",
    severity: "Medium",
    diet: "Fluids",
    med: "Steroids, humidifier",
    time: "3-7 days",
    curable: "Yes",
    remedy: "croup",
    remedyText: "Steam inhalation, humidifier, keep calm.",
  },
  {
    id: "rsv",
    name: "RSV (Respiratory Syncytial Virus)",
    severity: "Medium-High",
    diet: "Fluids",
    med: "Supportive care",
    time: "1-2 weeks",
    curable: "Yes",
    remedy: "rsv",
    remedyText: "Hydration, humidifier, monitor breathing.",
  },
  {
    id: "pertussis",
    name: "Pertussis (Whooping Cough)",
    severity: "High",
    diet: "Small frequent meals",
    med: "Antibiotics",
    time: "6-10 weeks",
    curable: "Yes",
    remedy: "pertussis",
    remedyText: "Antibiotics, humidifier, avoid irritants.",
  },
  {
    id: "pleurisy",
    name: "Pleurisy",
    severity: "Medium-High",
    diet: "Anti-inflammatory",
    med: "NSAIDs, treat cause",
    time: "1-2 weeks",
    curable: "Yes",
    remedy: "pleurisy",
    remedyText: "Rest, anti-inflammatory foods, pain relief.",
  },
  {
    id: "emphysema",
    name: "Emphysema",
    severity: "High",
    diet: "High calorie",
    med: "Bronchodilators, oxygen",
    time: "Chronic",
    curable: "No (manageable)",
    remedy: "emphysema",
    remedyText: "Quit smoking, pulmonary rehab, breathing exercises.",
  },
  {
    id: "pulmonary",
    name: "Pulmonary Embolism",
    severity: "Critical",
    diet: "Normal",
    med: "Anticoagulants",
    time: "Weeks-months",
    curable: "Treatable",
    remedy: "pulmonary",
    remedyText: "Emergency medical care — life-threatening!",
  },
  {
    id: "sarcoidosis",
    name: "Sarcoidosis",
    severity: "Medium-High",
    diet: "Anti-inflammatory",
    med: "Steroids if needed",
    time: "Variable",
    curable: "Sometimes",
    remedy: "sarcoidosis",
    remedyText: "Anti-inflammatory diet, vitamin D monitoring.",
  },
  {
    id: "sleep",
    name: "Sleep Apnea",
    severity: "Medium-High",
    diet: "Weight loss if needed",
    med: "CPAP machine",
    time: "Chronic",
    curable: "Manageable",
    remedy: "sleep",
    remedyText: "Weight loss, sleep on side, avoid alcohol.",
  },
  {
    id: "narcolepsy",
    name: "Narcolepsy",
    severity: "Medium",
    diet: "Regular meals",
    med: "Stimulants",
    time: "Lifelong",
    curable: "No (manageable)",
    remedy: "narcolepsy",
    remedyText: "Regular sleep schedule, short naps, medication.",
  },
  {
    id: "restless",
    name: "Restless Leg Syndrome",
    severity: "Low-Medium",
    diet: "Iron if deficient",
    med: "Dopamine agonists",
    time: "Chronic",
    curable: "Manageable",
    remedy: "restless",
    remedyText: "Iron supplements, leg massage, exercise.",
  },
];

// Export for modular use
if (typeof module !== "undefined" && module.exports) {
  module.exports = DISEASES_DATA;
}
